# interval is how often the watch subcommand should check for new posts. It should be represented as a string that can be parsed by Go's time.ParseDuration function.
# type is a required field that specifies the type of the source or destination.
# name is the name of the source or destination. It is ud to refer to the source or destination when running the command.
# overwrite is a boolean field that specifies whether to overwrite the file/post if it already exists. This is done by removing old files/posts that have the same title.
# blog_url is the URL of the blog
# content_dir is the directory where the markdown files are located
# git_dir, if set, will be used to push files to a Git repository. Normally, if you're running something like Hugo, this would be the root directory of your Hugo site (the top-level directory that contains .git)
# frontmatter_mapping is a table that can be used to customize the frontmatter (metadata). This is useful if your Hugo theme uses different frontmatter keys or if it's a frontmatter key that's not "officially" supported by Hugo and it's up to the theme to decide what key to use. I use Hugo as an example but in reality, this option could probably be used to make this compatible with any static site generator that uses frontmatter.
# generate_llm_descriptions is used to utilize Large Language Models to generate descriptions for Blogger posts as they don't have a description field accessible via the API.
# category_prefix dictates the prefix that Blogger labels should have to be turned into Hugo categories. For example, if you have a label called "category::foo" and the category_prefix is "category::", then the categories will be ["foo"]. Any labels that don't have the prefix will be turned into tags.
[[destinations]]
interval = '30s'
log_level = 'info'

[[destinations]]
blog_url = 'https://example.com'
name = 'blog'
overwrite = false
type = 'blogger'

[[destinations]]
content_dir = '/hugo-site/content/blog'
git_dir = '/hugo-site'
name = 'otherblog'
overwrite = false
type = 'markdown'

[destinations.frontmatter_mapping]
canonical_url = 'canonicalURL'
categories = 'categories'
date = 'date'
date_updated = 'lastmod'
description = 'description'
managed = 'managedByCrossBlogger'
tags = 'tags'
title = 'title'

[[sources]]
blog_url = 'https://example.com'
category_prefix = 'category::'
generate_llm_descriptions = true
name = 'someblog'
type = 'blogger'

[[sources]]
content_dir = 'content'
name = 'aBlogInMarkdown'
type = 'markdown'

[sources.frontmatter_mapping]
canonical_url = 'canonicalURL'
categories = 'categories'
date = 'date'
date_updated = 'lastmod'
description = 'description'
managed = 'managedByCrossBlogger'
tags = 'tags'
title = 'title'
