name: Go

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: 1.18
    - name: Cross compile
      uses: crazy-max/ghaction-xgo@v2
      with:
        xgo_version: latest
        go_version: 1.19
        dest: /home/runner/work/oauth-blogger/builds
        prefix: oauth-blogger
        targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64,windows/arm,windows/arm64,linux/arm,darwin/amd64
    - name: pwd
      run:  pwd
    - name: ls pwd
      run: ls
    - name: ls builds
      run: ls /home/runner/work/oauth-blogger/builds
    - name: ls /home/runner/work/oauth-blogger
      run: ls /home/runner/work/oauth-blogger
    - name: env
      run: env
    # - name: Build
    #   run: go build -v ./main.go